import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import AuthProvider from "@/providers/AuthProvider";

const inter = Inter({
  subsets: ["latin"], // Use the Latin subset
  variable: "--font-inter", // Optional: For CSS variables
});

export const metadata = {
  title: "FlowNote",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <AuthProvider>

        <div className="min-h-screen bg-background text-foreground">
          <div className="container mx-auto px-4 sm:px-8 md:px-16 lg:px-24 xl:px-32">
            <div className="wrapper py-2">
              <Navbar />
              {children}
              <Footer />
            </div>
          </div>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
